# Since incremental is not set, this config will replace the existing logging configuration.
# This means that any previous call to logging.basicConfig() (--loglevel) has no effect, and that
# any muting we have manually configured will be overridden.

version: 1

formatters:
  my_formatter:
    format: "--fullTest-- %(levelname)s:%(name)s:%(message)s"
  another_formatter:
    format: "--fullTest-- %(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  my_handler:
    class: logging.StreamHandler
    formatter: my_formatter

root:
  level: DEBUG
  handlers: [my_handler]

loggers:
  fmu.ensemble:
    level: INFO
  fmu.ensemble.realization:
    level: WARNING
  xtgeo:
    level: INFO
#  werkzeug:
#    level: DEBUG
